# Generated by Django 5.2.17 on 2026-10-02 05:36

import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_balance_userprofile_bonus_balance'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYSTACK', 'Paystack'), ('MPESA', 'M-Pesa'), ('CRYPTO', 'Crypto (USDT/BTC)'), ('WALLET', 'Wallet Balance'), ('MOCK', 'Development Mock')], max_length=20),
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=payments.models.generate_topup_reference, max_length=50, unique=True)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Credited'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
