# Generated by Django 4.2 on 2026-10-02 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_version', models.CharField(default='v1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('IRS', 'IRS Program'), ('SSA', 'SSA Program'), ('THIRD_PARTY', 'Licensed Third Party'), ('MOCK', 'Mock/Development')], max_length=50)),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('secret', models.CharField(blank=True, default='', max_length=255)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox/Test'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('timeout', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('requires_consent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_number', models.CharField(db_index=True, default=verification.models.generate_verification_number, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('AWAITING_CONSENT', 'Awaiting Consent'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='AWAITING_CONSENT', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Stores masked/minimized verification response')),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verification.consentrecord')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='accounts.userprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verification.verificationprovider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verification.verificationservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.verificationservice'),
        ),
    ]
