services:
  # 1-Click Free Web Service + Telegram Bot Worker
  - type: web
    name: dreydocs-web
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./run.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: USE_SQLITE
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: dreydocs-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        value: "8942516822"
      - key: ADMIN_TELEGRAM_USERNAMES
        value: "Dreydocbot"

databases:
  - name: dreydocs-db
    region: oregon
    plan: free
