# Generated by Django 5.2.17 on 2026-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_document',
            field=models.FileField(blank=True, null=True, upload_to='orders/custom_docs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_notes',
            field=models.TextField(blank=True, default='', help_text='Custom request notes from customer or admin'),
        ),
    ]
